### ISSUE TITLE
Unable to compile on Mac with Apple LLVM version 10.0.1 (clang-1001.0.46.4) on x86-64

### ISSUE THREAD

**Issue by kiranns** [xxsds/multi_index#2]
Mac OS version:
Darwin skiran-mac-0 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Compiler: 
> g++ -v 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

Error:
/Users/kiran/multi_index/multi_index/include/multi_idx/perm_3_1.hpp:49:32: error: constexpr variable cannot have
      non-literal type 'const perm<'\x03', '\x01'>::t_fun_vec_mi' (aka 'const array<unsigned long long (*)(unsigned
      long long), 3>')
        static constexpr t_fun_vec_mi mi_permute = {
